package com.kodilla.exception.io.test;

//public class SecondChallengeTestSuite {
//
////    // VOID! PLEASE IGNORE CODE BELOW !
////
////    @Test
////    void testProbablyIWillThrowException()  {
////        //GIVEN
////        SecondChallenge secondChallenge = new SecondChallenge();
////
////        //WHEN
////        String result = null;
////        try {
////            String s = secondChallenge.probablyIWillThrowException(4, 6);
////        } catch (Exception e) {
////            System.out.println("Error : " + e );
////        } finally {
////            System.out.println(secondChallenge);
////        }
////        //THEN
////        //????????????
////    }
////}
